### ISSUE TITLE
Multiple issues with the "Add node group" macro

### ISSUE THREAD

**Issue by hrjn** [dataiku/dss-plugin-eks-clusters#10]
* Adding a new node group via the macro is not possible unless you have properly configured your cluster (public) subnets with the `MapPublicIpOnLaunch`property enabled (visually translates into ticking the *"Enable auto-assign public IPv4 address"* box in the "Modify auto-assign IP" settings). There should be at least an explicit warning in the macro UI

* It's not possible to create additional node groups if the cluster subnets are all private
  * The macro fails with the following error:
      ```
      No export named your-cluster-name::SubnetsPublic found
      ```
      (if you try to reproduce the issue, you will need to manually delete the failed CF stack that was generated once you're done)

**Comment by amandineslx** [comment]
Feature to support fully-private clusters has been delivered in [plugin version `1.1.0`](https://github.com/dataiku/dss-plugin-eks-clusters/releases/tag/v1.1.0). These issues are not reproducible anymore
