### ISSUE TITLE
Update with new icon

### ISSUE THREAD

**Issue by alexcombessie** [dataiku/dss-plugin-eks-clusters#3]
A new icon is available in master:
https://github.com/dataiku/dip/blob/8a329c743447e5394f04cc78dbc54c67fe7c53c2/src/main/platypus/static/dataiku/css/font.less#L1504

To guarantee back-compatibility, you can use this syntax
"icon": "icon-amazon-elastic-kubernetes icon-cloud"

**Comment by alexcombessie** [comment]
👋  @FChataigner (small UX thing)

**Comment by alexcombessie** [comment]
Hello @jbelafa! 
Any chance we can use our custom icon (comes with DSS8)?
Cheers,
Alex

**Comment by alexcombessie** [comment]
Ping @PHHINCELIN @FChataigner - a very small UX thing that can be merged quickly

**Comment by hrjn** [comment]
@alexcombessie I'm closing this since it's taken care of in [the GPU PR](https://github.com/dataiku/dss-plugin-eks-clusters/pull/9).
